### ISSUE TITLE
Dublicate Support + appcompact version

### ISSUE THREAD

**Issue by cliffgr** [Leanplum/Leanplum-Android-SDK#110]
hello,
when i run : gradlew -q dependencies app:dependencies --configuration compile
You load the same lib with difference Version. Please check your Gradle file 
+--- com.leanplum:Leanplum:3.0.1
|    +--- com.android.support:support-v4:[22.0.0,26.1.0] -> 26.1.0 (*)
|    \--- com.android.support:appcompat-v7:[22.0.0,26.1.0] -> 26.1.0 (*)

**Comment by milos1290** [comment]
@cliffgr do you mean on `support-v4` and `appcompat-v7` ?

**Comment by cliffgr** [comment]
Both

**Comment by milos1290** [comment]
We use both support-v4 and appcompat-v7. The appcompat-v7 is dependent on support-v4. If you mean on `[22.0.0,26.1.0]` that is just a range of version we support.

**Comment by cliffgr** [comment]
Thanks :)
