### ISSUE TITLE
Can't compile app with Java 8

### ISSUE THREAD

**Issue by AlexZvonik** [Leanplum/Leanplum-Android-SDK#113]
When compiling my app with Java 8 enabled, i'm getting weird error:

`Error:Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/4.jar --output /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/desugar/debug/5.jar --input /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/0.jar --output /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/desugar/debug/1.jar --input /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/2.jar --output /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/desugar/debug/3.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/classes/debug --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/0.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/1.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/2.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/3.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/4.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/5.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/6.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/7.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/8.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/9.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/10.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/11.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/12.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/13.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/14.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/15.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/16.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/17.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/18.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/19.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/20.jar --classpath_entry /home/alex/AndroidStudioProjects/TestJava8/app/build/intermediates/transforms/stackFramesFixer/debug/21.jar --bootclasspath_entry /home/alex/Android/Sdk/platforms/android-26/android.jar --bootclasspath_entry /home/alex/Android/Sdk/platforms/android-26/optional/org.apache.http.legacy.jar --bootclasspath_entry /home/alex/Android/android-studio/jre/jre/lib/resources.jar --bootclasspath_entry /home/alex/Android/android-studio/jre/jre/lib/rt.jar --bootclasspath_entry /home/alex/Android/android-studio/jre/jre/lib/jsse.jar --bootclasspath_entry /home/alex/Android/android-studio/jre/jre/lib/jce.jar --bootclasspath_entry /home/alex/Android/android-studio/jre/jre/lib/charsets.jar --min_sdk_version 16 --desugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}`

This error is reproducible only when `implementation "com.leanplum:Leanplum:+"` is in my build.gradle

**Comment by benmarten** [comment]
Not sure why this happens. The actual stack trace does not show that its related to core leanplum sdk.
We are using java8 here by default too...
Can you try to build the sdk from source, and see if you get any other errors/insights? 
https://github.com/Leanplum/Leanplum-Android-SDK#build-the-sdk

**Comment by AlexZvonik** [comment]
Hi @benmarten 
I was able to build the sdk from source (from master).
But when i put Leanplum.jar into my /libs folder - i got the same error. (implementation "com.leanplum:Leanplum:+" was removed from my build.gradle)

**Comment by yu-guseva-softteco** [comment]
I have the same issue. Any updates?

**Comment by milos1290** [comment]
I can confirm that issue is not present when library is built using AndroidStudio 3.0 and Gradle 4.1. This PR should fix the issue #112

**Comment by AlexZvonik** [comment]
Hi @benmarten 
Any update regarding this issue?

**Comment by Enuviel** [comment]
Hi @AlexZvonik,
We will add #112 to our next release, and as @milos1290  mention above - it will help.

**Comment by Enuviel** [comment]
@AlexZvonik, btw if you change minSdkVersion in your test project to 24 it will compile...

**Comment by AlexZvonik** [comment]
@Enuviel thanks!
Unfortunately i can't change minSdkVersion so i will wait for the next release.

**Comment by Enuviel** [comment]
@AlexZvonik Retrolambda? AS3 will show some warning, but that should work until next major release.

**Comment by vevo-sergei-kostin** [comment]
We are having the same problem. Using AndroidStudio 3.0 and Gradle 4.1/ Java 8, LeanPlum 3.0.1 
Retrolambda solves the problem, thank you @Enuviel

**Comment by atoropov** [comment]
Hi, can you please tell when are planning next release? Thanks.

**Comment by benmarten** [comment]
It's in our current sprint. I think we'll cut a new release branch and start QA today. If there are no issues, release should be coming in a few days...

**Comment by bogus** [comment]
Do you have any updates on this? Thanks!

**Comment by Enuviel** [comment]
https://github.com/Leanplum/Leanplum-Android-SDK/releases/tag/3.0.2

**Comment by AlexZvonik** [comment]
@Enuviel 
This bug can be reproduced on the latest SDK version

**Comment by Enuviel** [comment]
Hi @AlexZvonik is this issue still present for you?
