### ISSUE TITLE
No way to trigger "Open Action" for Inbox Message

### ISSUE THREAD

**Issue by Stenopolz** [Leanplum/Leanplum-Android-SDK#114]
There is an option "Open Action" for Inbox messages, but I can't access it from LeanplumInboxMessage class, there are no special getters and getData method returns null. What is the designated way to trigger "Open Action" ?

**Comment by Enuviel** [comment]
Hi @Stenopolz, please contact your CSM/TSE with this question.
Method getData is not related to  "Open Action", this is for "Data" at "Advanced options".

**Comment by PavelShchors** [comment]
@Enuviel Thank you. We will contact our CSM.
