### ISSUE TITLE
Get Device ID

### ISSUE THREAD

**Issue by timatoe** [Leanplum/Leanplum-Android-SDK#117]
Hi,

I am trying to get the device ID from the leanplum sdk after Leanplum.start(); has been called. 
Could you let me know how I can get the current device ID?

I am looking for the android equivalent to this code below:

```
/**
 * Returns the deviceId in the current Leanplum session. This should only be called after
 * [Leanplum start].
 */
+ (NSString *)deviceId;
```

Thank you

**Comment by Enuviel** [comment]
Thanks @timatoe!
