### ISSUE TITLE
Refine ProGuard rules

### ISSUE THREAD

**Issue by ming13** [Leanplum/Leanplum-Android-SDK#158]
I see that the SDK includes consumer ProGuard rules (which is great), but they are too loose (if it makes sense). Specifically I’m talking about these ones:

```
-keep class android.support.v7.** { *; }
-keep interface android.support.v7.** { *; }
-keep class com.leanplum.** { *; }
```

Basically you are telling ProGuard to keep everything from the support library and this SDK which is actually equivalent to not doing ProGuard at all.

**Comment by e7mac** [comment]
Done in #244
