### ISSUE TITLE
Add option to resync/ignore messages if target attributes (known locally) change

### ISSUE THREAD

**Issue by Mugurell** [Leanplum/Leanplum-Android-SDK#168]
Currently, as per https://support.leanplum.com/hc/en-us/articles/115003470566-How-and-when-are-targets-evaluated- 
"if the user’s relevant segment criteria changes during that session, the user won’t be re-evaluated as a target till the start of their next session."

This can badly affect user experience if let's say through a message we instruct him to do something, he does that, but still continues to receive messages about that.

There is no solution to do this while the app is running and there is no solution to easily restart LeanPlum to force a refetch of updated messages.

**Comment by e7mac** [comment]
Hey @Mugurell, this page might have a solution to what you are trying to achieve: https://docs.leanplum.com/reference#syncing-with-leanplum-mid-session

Let us know if you have any trouble with that!
