### ISSUE TITLE
Deprecated FCM token handling

### ISSUE THREAD

**Issue by ipereziriarte** [Leanplum/Leanplum-Android-SDK#247]
Hi,
I was migrating my app from GCM to FCM and I realized that the token handling is based on a deprecated Firebase class.

Currently, the token creation and renewal is being handled by `LeanplumPushFcmListenerService` that extends `FirebaseInstanceIdService`

However, since June 28, 2018, FirebaseInstanceIdService class was deprecated in favor of overriding the `onNewToken` method of `FirebaseMessagingService`.
This was released in Cloud Messaging[ version 17.1.0 ](https://firebase.google.com/support/release-notes/android)
## Expected Behavior
Change the way of handling tokens in FCM implementation and remove `LeanplumPushFcmListenerService`
Override `onNewToken` in FirebaseMessagingService

## Actual Behavior
Clients need to implement 2 classes, even if one of them was deprecated almost 3 months ago

I can make a PR with the changes if you like it.

**Comment by e7mac** [comment]
We welcome community contributions to the SDK! Let's make it better for everyone
