### ISSUE TITLE
Crash NPE in LeanplumInbox

### ISSUE THREAD

**Issue by lucas34** [Leanplum/Leanplum-Android-SDK#274]
I'm having a quite high bug report with this following crash

```
Caused by java.lang.NullPointerExceptionAttempt to invoke virtual method 'boolean com.leanplum.LeanplumInboxMessage.isRead()' on a null object reference
  | com.leanplum.LeanplumInbox.unreadMessages (LeanplumInbox.java:451)
  | com.leanplum.LeanplumInbox.unreadMessages (LeanplumInbox.java:153)

```

I'm not sure about the step to reproduce but can we have a null check or prevent this crash ?

LP version: 4.0.2

**Comment by aafrooze** [comment]
Thanks for reporting this. We're on it!

**Comment by lucas34** [comment]
I saw that this has been fix. 
When is the expected release with this fix ?

**Comment by lucas34** [comment]
Now released. Thanks !
