### ISSUE TITLE
Inbox content is retain when changing user

### ISSUE THREAD

**Issue by lucas34** [Leanplum/Leanplum-Android-SDK#284]
Hi,

When a user logout and login with a different account, Leanplum inbox still return the content of the previous user.

I tried to call forceUpdate and so on but nothing help.

Any advice on it ?

**Comment by nzagorchev** [comment]
Hi,
Ensure when the new user has logged in, that setUserId is called and then execute forceContentUpdate to get the variables, messages, inbox for that user.

You can also troubleshoot what messages are returned for the user in question using the bellow API call.
The call requires the following parameters:
Url: https://www.leanplum.com/api?action=getNewsfeedMessages
appId: the application id (app_...)
clientKey: the production key (prod_...)
apiVersion: the current one is 1.0.6
deviceId: the device id of the user
userId: the user Id

https://www.leanplum.com/api?action=getNewsfeedMessages&appId=APP_ID&clientKey=PROD_KEY&apiVersion=1.0.6&deviceId=DEVICE_ID&userId=USER_ID

If you need further assistance, please submit a support ticket.
