### ISSUE TITLE
Please add a changelog?

### ISSUE THREAD

**Issue by tommytcchan** [Leanplum/Leanplum-Android-SDK#29]
Hi there, we are upgrade from 1.5.x to the latest (2.2.2) but I don't see a changelog file anywhere. I want to be able to ensure the upgrade doesn't affect our release. Can someone from the leanplum team please post that?

Best

T

**Comment by benmarten** [comment]
The cangelogu under /releases is just existing since the last release, when we open sourced.

For the complete changeling please look here: https://support.leanplum.com/hc/en-us/articles/213531666-Android-SDK-release-notes=)
or in the dashboard menu under `Help Center/Whats New`
