### ISSUE TITLE
consumer-proguard-rules.pro keeps unnecessary classes.

### ISSUE THREAD

**Issue by igorab** [Leanplum/Leanplum-Android-SDK#33]
SDK has two proguard rules:

- [`proguard-rules.pro`](https://github.com/Leanplum/Leanplum-Android-SDK/blob/02e082d77590370ae6fce75fd308752d69efb208/AndroidSDK/proguard-rules.pro)
- [`consumer-proguard-rules.pro`](https://github.com/Leanplum/Leanplum-Android-SDK/blob/02e082d77590370ae6fce75fd308752d69efb208/AndroidSDK/consumer-proguard-rules.pro)

`proguard-rules.pro` seems to be good and keeps only necessary classes, however proguard rules for consumers `consumer-proguard-rules.pro` seem to keep all the classes from SDK which in our case required enabling multiplex for our release configuration which we certainly want to avoid.

**Comment by milos1290** [comment]
The SDK we are shipping is already proguarded without classes that are needed to be kept, so we need to have additional keep for our classes in `consumer-proguard-rules.pro`, otherwise our public classes will be stripped again, which could cause some of the SDK features not work at all.

**Comment by igorab** [comment]
Ok, makes sense. Thanks!
