### ISSUE TITLE
FCM Sdk 4.0.0 crashes in runtime with AndroidX migrated project

### ISSUE THREAD

**Issue by lworx-stanley** [Leanplum/Leanplum-Android-SDK#333]
## Expected Behavior

SDK should not crash on receiving pushNotification.

## Actual Behavior

`Fatal Exception: java.lang.VerifyError: Rejecting class com.modcloth.PushNotification.ModClothFirebaseMessagingService that attempts to sub-type erroneous class com.leanplum.LeanplumPushFirebaseMessagingService (declaration of 'com.modcloth.PushNotification.ModClothFirebaseMessagingService' appears in /data/app/com.modcloth-0aDbPlexg98KdD-o0Ga9aw==/base.apk!classes2.dex)`

## Steps to Reproduce the Problem

 1 Migrate project to AndroidX
 2 Existing Leanplum-fcm SDK 4.0.0
 3 Access any SDK class at runtime

## Specifications

- Version: 4.0.0
- Platform: Android 9.0

**Comment by e7mac** [comment]
This is a known issue in version 4.3.0. This issue was resolved in 4.3.1
We haven't seen this issue in 4.0.0. However, please could you update to 4.3.1 or above and see if that resolves the issue?
