### ISSUE TITLE
Question: Uninstall Tracking

### ISSUE THREAD

**Issue by erchenger** [Leanplum/Leanplum-Android-SDK#336]
It looks like when we turn on uninstall tracking at like 4AM our users are getting blank notifications. Is there a way to determine uninstall tracking notifications being sent to us. It seems like maybe that would be done via an `empty` message but wasn't sure exactly what to look for.

**Comment by nzagorchev** [comment]
The Uninstall tracking works by sending a silent push notification. It should not be visible by the client. If the push appears as empty in the notification drawer, please check if you have customized the default push service. 
If you need further assistance, please submit a support ticket.

[https://docs.leanplum.com/docs/enabling-uninstall-tracking](https://docs.leanplum.com/docs/enabling-uninstall-tracking)
> How do Uninstalls work?
> Leanplum runs a job every 24 hours to check if each user’s push token is still valid. We only track an Uninstall if the response we get from Apple or Google indicates that the user's push token is "Unregistered" (which is caused by a user uninstalling the app).
