### ISSUE TITLE
Delete pro guard section from documentation

### ISSUE THREAD

**Issue by igorab** [Leanplum/Leanplum-Android-SDK#34]
In [documentation](https://www.leanplum.com/docs/android/setup#edit-your-application-class) in section `Add Proguard configuration` you write about add `proguard-project.txt` file with pro guard rules, but your library already has rules in aar.

**Comment by benmarten** [comment]
Yes I agree, this can be removed if you install our SDK via AAR, which is the default. Thanks for pointing out.

@mattleanplum May I please ask you to either remove the section in our documentation or explicitly mark it as JAR only? Thanks

**Comment by benmarten** [comment]
Modifications to the docs have been landed in our internal master branch and will go live with next weeks release.
