### ISSUE TITLE
Delete android:label from application section on AndroidManifest.xml

### ISSUE THREAD

**Issue by igorab** [Leanplum/Leanplum-Android-SDK#35]
I see `<application android:label="@string/app_name">` in your AndroidManifest.xml.  Please delete it.
Because all android application used your sdk have to add `tools:replace="android:label"` in application section on AndroidManifest.xml.

**Comment by benmarten** [comment]
We were not able to reproduce your issue, as we tested it and in the `Merge Manifest` view in Android Studio, it automatically replaces it with the actual app name in our Test App.

However its seems that this label is not needed for a Android library, hence we will try to remove it in the next SDK version. Thanks for reporting.

**Comment by Enuviel** [comment]
https://github.com/Leanplum/Leanplum-Android-SDK/pull/38

**Comment by igorab** [comment]
Thanks! A think I reproduced it because we set it `android:label` in gradle.
