### ISSUE TITLE
Maybe it would be nice to split your sdk in some modules? 

### ISSUE THREAD

**Issue by igorab** [Leanplum/Leanplum-Android-SDK#40]
Maybe it would be nice to split your sdk in some modules? The first candidates: firebase and GCM push messages. Usually only one type of push is used in one application.

**Comment by milos1290** [comment]
This is actually something we discussed internally. We will definitely split some of the SDK features into separate modules, though there is no ETA on that.

**Comment by Enuviel** [comment]
Released in 4.0.0.
