### ISSUE TITLE
ClassCastException when reading number variables

### ISSUE THREAD

**Issue by MRezaNasirloo** [Leanplum/Leanplum-Android-SDK#552]
## Expected Behavior
Get an Integer or Double value from leanplum variable using 
```
private val _variable: Var<Double/Int?> = Var.define("variable", null)
```

## Actual Behavior
Crashing with an exception:
```
Fatal Exception: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
```
or 
```
Fatal Exception: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
```
This doesn't happen all time, most of the time it works

## Steps to Reproduce the Problem

  1. Create a number on variable dashboard with the value of say 50
  2. `private val _variable: Var<Double/Int?> = Var.define("variable", null)`
 

## Specifications

  - Version: 7.1.1
  - Platform: Android (any version)
  - Subsystem: ?

**Comment by hborisoff** [comment]
@MRezaNasirloo
Can you provide the whole stacktrace?

Can you test using a specific default value (let say 0 for integer), because I noticed that the model behind `Var` cannot deduce the type of the variable correctly when you pass `null` as default value.

Thank you for your feedback.
